# Generated by Django 3.1.1 on 2022-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_auto_20200925_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='poster',
            field=models.URLField(max_length=500),
        ),
    ]
